src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date d'arrivée doit être au format date")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieure à la date d'aujourd'hui", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date de départ doit être au format date")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être ultérieure à la date d'arrivée")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     */
    private $comment;

    /**
     * Callback appelé à chaque création de réservation
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            // prix * nb jours
            $this->amount = $this->ad->getPrice() * $this->getDuration() ;
        }
    }

    public function isBookableDates()
    {
        // connaitre les dates impossible
        $notAvailableDays = $this->ad->getNotAvailableDays();

        // comparer les dates choisies avec les dates impossibles
        $bookingDays = $this->getDays();

        $formatDay = function($day) {
            return $day->format('Y-m-d');
        };

        $days = array_map($formatDay, $bookingDays);

        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Permet de récupérer le tableau des jours correspondants à la réservation
     *
     * @return array
     */
    public function getDays()
    {
        $result = range(
          $this->startDate->getTimestamp(),
          $this->endDate->getTimestamp(),
          24 * 60 * 60
        );

        $days = array_map (function($dayTimestamp){
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $result);

        return $days;
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);

        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Cet email est déjà utilisé"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre nom")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez renseigner une url valide")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Votre introduction doit contenir au minimum 10 caratères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10, minMessage="Votre introduction doit contenir au minimum 10 caratères")

     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Le mot de passe ne correspond pas")
     */
    public $passwordConfirm;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AdLike", mappedBy="user")
     */
    private $likes;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * Permet d'initialiser le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug() {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role){
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    /**
     * @inheritDoc
     */
    public function getPassword()
    {
        return $this->hash;
    }

    /**
     * @inheritDoc
     */
    public function getSalt(){}

    /**
     * @inheritDoc
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials(){}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|AdLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(AdLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(AdLike $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     *
     * @param Ad $ad
     * @param Request $request
     * @param ObjectManager $manager
     * @return Response
     */
    public function book(Ad $ad, Request $request, ObjectManager $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();

            $booking->setBooker($user)
                    ->setAd($ad);

            // Si les dates sont non disponibles, erreur
            if (!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    'Les dates choisies sont déjà réservées'
                );
            }
            else {
                $manager->persist($booking);
                $manager->flush();

                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(),
                    'success' => true]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher la page d'une réservation
     *
     * @Route("/booking/{id}", name="booking_show")
     *
     * @param Booking $booking
     * @param Request $request
     * @param ObjectManager $manager
     * @return Response
     */
    public function show(Booking $booking, Request $request, ObjectManager $manager)
    {
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre commentaire a bien été pris en compte !'
            );
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : {{ ad.title }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />
{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <div class="card p-3">
                    <h1 class="card-header">Réserver l'annonce : <b>{{ ad.title }}</b></h1>
                    <div class="card-body">
                        <div class="alert alert-info alert-dismissible mb-4 px-3">
                            <button type="button" class="close pl-0" data-dismiss="alert">&times;</button>
                            <i class="fas fa-info-circle"></i>
                            Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}</strong>
                        </div>
                        {{ form_start(form) }}
                        <div class="alert alert-secondary">
                            <h4>Choisissez vos dates</h4>
                            <div class="row">
                                <div class="col-md-6">
                                    {{ form_row(form.startDate) }}
                                </div>
                                <div class="col-md-6">
                                    {{ form_row(form.endDate) }}
                                </div>
                            </div>
                            <h4 class="mt-3">Montant du séjour : <span id="amount">...</span> &euro;</h4>
                            <span id="days">0</span> nuit(s) à {{ ad.price | number_format(2, ',', ' ') }} &euro; par nuit
                            <h4 class="mt-3">Commentaire</h4>
                            {{ form_row(form.comment) }}
                            <button type="submit" class="btn btn-info">Réserver</button>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('#booking_startDate, #booking_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                        "{{ day.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });
            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });

        function calculateAmount() {
            // on revert en format anglais
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

            if (startDate && endDate && startDate < endDate) {
                const DAY_TIME = 24 * 60 * 60 * 1000;

                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days * {{ ad.price }};

                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR'));
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre réservation (n°{{ booking.id }}){% endblock %}

{% block body %}
    {% set ad = booking.ad %}
    {% set author = ad.author %}

    {% if app.request.query.get('success') %}
        <div class="container mt-5">
            <div class="row">
                <div class="offset-md-2 col-md-8">
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <i class="fas fa-info-circle"></i>
                        <h4 class="alert-heading">Bravo !</h4>
                        <div>
                            Votre réservation auprès de
                            <a href="{{ path('user_show', {'slug': author.slug}) }}"><strong>{{ author.fullName }}</strong></a>
                            pour l'annonce
                            <a href="{{ path('ads_show', {'slug': ad.slug}) }}"><strong>{{ ad.title }}</strong></a>
                            a bien été prise en compte.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8">
                <div class="card p-3">
                    <h1 class="card-header">Votre réservation n°{{ booking.id }}</h1>
                    <div class="card-body">
                        <div class="alert alert-info alert-dismissible mb-4">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <i class="fas fa-info-circle"></i>
                            Consulter les détails de votre réservation
                        </div>
                        <dl class="row">
                            <dt class="col-md-4">Numéro</dt>
                            <dd class="col-md-8">{{ booking.id }}</dd>
                            <dt class="col-md-4">Date d'arrivée</dt>
                            <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                            <dt class="col-md-4">Date de départ</dt>
                            <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                            <dt class="col-md-4">Nombre de nuits</dt>
                            <dd class="col-md-8">{{ booking.duration }}</dd>
                            <dt class="col-md-4">Montant total</dt>
                            <dd class="col-md-8">{{ booking.amount | number_format(2, ',', ' ') }} &euro;</dd>
                            <dt class="col-md-4">Commentaire</dt>
                            <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dd>
                        </dl>
                    </div>
                </div>
                <hr class="bg-light mt-3">
                <div class="card p-3">
                    <h1 class="card-header">Votre hébergement</h1>
                    <div class="card-body">
                        <div class="alert alert-info alert-dismissible mb-4">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <i class="fas fa-info-circle"></i>
                            Consulter les détails de votre hébergement
                        </div>
                        <a href="{{ path('ads_show', {'slug': ad.slug}) }}" class="text-info"><h4>{{ ad.title }}</h4></a>
                        <img src="{{ ad.coverImage }}" alt="Image de {{ ad.title }}" class="img-fluid mb-4">
                        {{ ad.content | raw }}
                        <a href="{{ path('ads_show', {'slug': ad.slug}) }}" class="btn btn-info text-decoration-none">Plus d'informations</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card p-3">
                    <h1 class="card-header">Votre hôte</h1>
                    <div class="card-body px-0">
                        <div class="card border-info p-3">
                            <div class="card-header d-flex flex-column align-items-center">
                                <img src="{{ author.picture }}" class="rounded-circle" width="100px" alt="Avatar de {{ author.fullName }}">
                                <div class="my-3 text-center">
                                    <h2 class="my-0">{{ author.fullName }}</h2>
                                    <div class="text-muted">{{ author.email }}</div>
                                </div>
                                <div class="badge badge-info mx-auto">{{ author.ads |length }} annonces</div>
                            </div>
                            <div class="card-body">
                                {{ author.description | raw }}
                                <a href="{{ path('user_show', {'slug': author.slug}) }}" class="btn btn-info text-decoration-none">
                                    Plus d'infos sur {{ author.firstName }}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <hr class="bg-light mt-3">
                <div class="card border-info p-3" id="comment">
                    <h1 class="card-header">Votre avis</h1>
                    <div class="card-body">
                        <div class="alert alert-info alert-dismissible mb-4 px-3">
                            <button type="button" class="close pl-0" data-dismiss="alert">&times;</button>
                            <i class="fas fa-info-circle"></i>
                            Consulter votre commentaire
                        </div>
                        {% if date() > date(booking.endDate) %}
                            {% set comment = booking.ad.commentFromAuthor(app.user) %}
                            {% if comment is not null %}
                                <strong>Note : </strong>
                                {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                                <blockquote class="mt-3">
                                    {{ comment.content }}
                                </blockquote>
                            {% else %}
                                {{ form_start(form) }}
                                {{ form_widget(form) }}
                                <button type="submit" class="btn btn-info">Envoyer</button>
                                {{ form_end(form) }}
                            {% endif %}
                        {% else %}
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <i class="fas fa-info-circle"></i>
                                <h4 class="alert-heading">Désolé !</h4>
                                <div>Vous ne pouvez pas noter cette annonce tant que votre voyage n'est pas terminé.</div>
                            </div>
                            <p>Vous ne pouvez pas noter cette annonce tant que votre voyage n'est pas terminé</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}