src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Une annonce contient déjà ce titre"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *     min=10,
     *     max=255,
     *     minMessage="Le titre doit contenir au minimum 10 caractères",
     *     maxMessage="Le titre doit contenir au maximum 255 caractères"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *     min=10,
     *     max=255,
     *     minMessage="L'introduction doit contenir au minimum 10 caractères",
     *     maxMessage="L'introduction doit contenir au maximum 255 caractères"
     * )
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AdLike", mappedBy="ad")
     */
    private $likes;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    /**
     * Permet de savoir si l'annonce est likée par un user
     *
     * @param User $user
     * @return bool
     */
    public function isLikedByUser(User $user)
    {
        foreach ($this->likes as $like) {
            if ($like->getUser() === $user) return true;
        }

        return false;
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if ($comment->getAuthor() === $author) return $comment;
        }

        return null;
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour une annonce
     *
     * @return float|int
     */
    public function getAvgRatings()
    {
        // calculer somme notes
        $somme = array_reduce($this->comments->toArray(), function ($total, $comment){
            return $total + $comment->getRating();
        }, 0);

        // division pour la moyenne
        if (count($this->comments) > 0) return $somme / count($this->comments);

        return 0;
    }

    /**
     * Permet d'obtenir un tableau des jours non disponibles pour cette annonce
     *
     * @return array
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];

        foreach ($this->bookings as $booking) {
            // Calculer les jours entre date d'arrivée et départ
            $result = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );

            $days = array_map(function ($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $result);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }

    /**
     * Permet d'initialiser le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug() {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|AdLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(AdLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setAd($this);
        }

        return $this;
    }

    public function removeLike(AdLike $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getAd() === $this) {
                $like->setAd(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'title',
                TextType::class,
                $this->getConfiguration('Titre', 'Entrez votre titre')
            )
            ->add(
                'slug',
                TextType::class,
                $this->getConfiguration('Slug', 'Entrez votre slug', [
                    'required' => false
                ])
            )
            ->add(
                'coverImage',
                UrlType::class,
                $this->getConfiguration('URL de l\'image', 'Entrez votre url de l\'image')
            )
            ->add(
                'introduction',
                TextType::class,
                $this->getConfiguration('Introduction', 'Entrez votre introduction')
            )
            ->add(
                'content',
                TextareaType::class,
                $this->getConfiguration('Description', 'Entrez votre description')
            )
            ->add(
                'rooms',
                IntegerType::class,
                $this->getConfiguration('Nombre de chambres', 'Entrez votre nombre de chambres')
            )
            ->add(
                'price',
                MoneyType::class,
                $this->getConfiguration('Prix par nuit', 'Entrez votre prix par nuit')
            )
            ->add(
                'images',
                CollectionType::class,
                [
                    'entry_type' => ImageType::class,
                    'allow_add' => true,
                    'allow_delete' => true
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\AdLike;
use App\Entity\Image;
use App\Form\AdType;
use App\Repository\AdLikeRepository;
use App\Repository\AdRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     * @param AdRepository $repo
     * @return Response
     */
    public function index(AdRepository $repo)
    {
        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }

    /**
     * Permet de liker ou unliker une annonce
     *
     * @Route("/ads/{id}/like", name="ads_like")
     *
     * @param Ad $ad
     * @param ObjectManager $manager
     * @param AdLikeRepository $repo
     * @return JsonResponse
     */
    public function like(Ad $ad, ObjectManager $manager, AdLikeRepository $repo)
    {
        $user = $this->getUser();

        if (!$user) {
            return $this->json([
                'code' => 403,
                'message' => "Unauthorized"
            ], 403);
        }

        if ($ad->isLikedByUser($user)) {
            $like = $repo->findOneBy([
                'ad' => $ad,
                'user' => $user
            ]);

            $manager->remove($like);
            $manager->flush();

            return $this->json([
                'code' => 200,
                'message' => 'Like supprimé',
                'likes' => $repo->count(['ad' => $ad])
            ], 200);
        }

        $like = new AdLike();
        $like->setAd($ad)
            ->setUser($user);

        $manager->persist($like);
        $manager->flush();

        return $this->json([
            'code' => 200,
            'message' => 'Like ajouté',
            'likes' => $repo->count(['ad' => $ad])
        ], 200);
    }

    /**
     * Permet de créer une annonce
     *
     * @Route("/ads/new", name="ads_create")
     * @IsGranted("ROLE_USER")
     *
     * @param Request $request
     * @param ObjectManager $manager
     * @return Response
     */
    public function create(Request $request, ObjectManager $manager) {
        $ad = new Ad();

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $ad->setAuthor($this->getUser());

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée !"
            );

            return $this->redirectToRoute('ads_show', [
               'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher le form d'édition
     *
     * @Route("ads/{slug}/edit", name="ads_edit")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous ne pouvez pas modifier cette annonce")
     *
     * @param Ad $ad
     * @param Request $request
     * @param ObjectManager $manager
     * @return Response
     */
    public function edit(Ad $ad, Request $request, ObjectManager $manager) {
        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été modifiée !"
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Permet d'afficher une seule annonce
     *
     * @Route("/ads/{slug}", name="ads_show")
     *
     * @param Ad $ad
     * @return Response
     */
    public function show(Ad $ad) {
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    }

    /**
     * Permet de supprimer une annonce
     *
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous ne pouvez pas supprimer cette annonce")
     *
     * @param Ad $ad
     * @param ObjectManager $manager
     * @return RedirectResponse
     */
    public function delete(Ad $ad, ObjectManager $manager)
    {
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée !"
        );

        return $this->redirectToRoute('ads_index');
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug': ad.slug}) %}

<div class="col-md-6 col-lg-4">
    <div class="card border-info mb-3">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong>{{ ad.price | number_format(2, ',', ' ') }} &euro; / nuit</strong>
            <br>
            {% if ad.comments|length > 0 %}
                {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>
        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="{{ ad.title }}" class="img-fluid">
        </a>
        <div class="card-body bg-secondary p-0">
            <div class="p-3">
                <a href="{{ url }}" class="text-info">
                    <h4 class="card-title">{{ ad.title }}</h4>
                </a>
                <p class="card-text">{{ ad.introduction }}</p>
                <a href="{{ url }}" class="btn btn-info mb-3">En savoir plus</a>
                <div class="float-right mb-3 ml-1">
                    <a href="{{ path('ads_like', {'id': ad.id}) }}" class="js-link">
                        {% if app.user and ad.isLikedByUser(app.user) %}
                            <div class="btn btn-danger">
                                <i class="fas fa-thumbs-down m-0 mr-1"></i>
                                <span class="js-label">Je n'aime plus</span>
                                <span class="js-likes"> ({{ ad.likes | length }})</span>
                            </div>
                        {% else %}
                            <div class="btn btn-success">
                                <i class="fas fa-thumbs-up m-0 mr-1"></i>
                                <span class="js-label">J'aime</span>
                                <span class="js-likes"> ({{ ad.likes | length }})</span>
                            </div>
                        {% endif %}
                    </a>
                </div>
                {% if app.user and app.user == ad.author %}
                    <div class="float-right mb-3">
                        <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-info mr-1"><i class="fas fa-edit m-0"></i></a>
                        <a href="{{ path('ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger"
                           onclick="return confirm(`Etes-vous sûr de vouloir supprimer l'annonce : {{ ad.title }} ?`)"><i class="fas fa-trash m-0"></i></a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
    <h6><i>Ajouter vos images :</i></h6>
    <input type="hidden" id="widgets_counter" value="0">
    <div class="form-group">
        <button type="button" id="ad_image" class="btn btn-info">Ajouter une image</button>
    </div>
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        {{ form_errors(form) }}
        <div class="row">
            <div class="col-md-11">
                <div class="row">
                    <div class="col-md-6 mb-3 mb-md-0">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col-md-6 mb-3 mb-md-0">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-md-1 text-md-right pl-md-0">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">x</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="offset-md-2 col-md-8">
                <div class="card border-info p-3">
                    <h1 class="card-header">Modifier une annonce</h1>
                    <div class="card-body">
                        <div class="alert alert-info alert-dismissible mb-4 px-3">
                            <button type="button" class="close pl-0" data-dismiss="alert">&times;</button>
                            <i class="fas fa-info-circle"></i>
                            Vous pouvez modifier l'annonce "<b>{{ ad.title }}</b>"
                        </div>
                        {{ form_start(form) }}
                        {{ form_widget(form) }}
                        <button type="submit" class="btn btn-info">Enregistrer</button>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('build/js/ad.js') }}"></script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            <div class="card p-3">
                <h1 class="card-header">Voici les annonces de nos hôtes !</h1>
                <div class="card-body">
                    <div class="row">
                        {% for ad in ads %}
                            {% include 'ad/_ad.html.twig' %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}
    <div class="adtitle" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url({{ ad.coverImage }})">
        <div class="container">
            <h1>{{ ad.title }}</h1>
            <p>{{ ad.introduction }}</p>
            <p class="h2"><strong>{{ ad.rooms }} chambres</strong> pour <strong>{{ ad.price | number_format(2, ',', ' ') }} &euro;</strong> par nuit</p>
            <a href="{{ path('booking_create', {'slug': ad.slug}) }}" class="btn btn-info mr-3 my-3">Réserver</a>
            {% if app.user and app.user == ad.author %}
                <div class="my-3 float-md-right">
                    <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-info mr-3">Modifier</a>
                    <a href="{{ path('ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger"
                       onclick="return confirm(`Etes-vous sûr de vouloir supprimer l'annonce : {{ ad.title }} ?`)">Supprimer</a>
                </div>
            {% endif %}
            <a href="{{ path('ads_like', {'id': ad.id}) }}" class="js-link">
                {% if app.user and ad.isLikedByUser(app.user) %}
                    <div class="btn btn-danger">
                        <i class="fas fa-thumbs-down m-0 mr-1"></i>
                        <span class="js-label">Je n'aime plus</span>
                        <span class="js-likes"> ({{ ad.likes | length }})</span>
                    </div>
                {% else %}
                    <div class="btn btn-success">
                        <i class="fas fa-thumbs-up m-0 mr-1"></i>
                        <span class="js-label">J'aime</span>
                        <span class="js-likes"> ({{ ad.likes | length }})</span>
                    </div>
                {% endif %}
            </a>
        </div>
    </div>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 mb-5">
                <div class="card">
                    <div class="card-body">
                        {{ ad.content|raw }}
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for image in ad.images %}
                                    <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active"{% endif %}></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner">
                                {% for image in ad.images %}
                                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                                        <img src="{{ image.url }}" class="d-block" alt="{{ image.caption }}">
                                        <div class="carousel-caption d-none d-md-block w-100 p-2">
                                            <h5>{{ ad.title }}</h5>
                                            <p>{{ image.caption }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
                <hr class="bg-light my-4">
                <div class="card border-info p-3">
                    <h5 class="card-header">Les commentaires de nos visiteurs</h5>
                    <div class="card-body">
                        {% if ad.comments|length > 0 %}
                            <div class="alert alert-info">
                                <h4 class="alert-heading text-center">
                                    <div class="row align-items-center">
                                        <div class="col">Note globale donnée par nos visiteurs</div>
                                        <div class="col">
                                            {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
                                            <br>
                                            <small>(Calculée sur {{ ad.comments|length }} avis)</small>
                                        </div>
                                    </div>
                                </h4>
                            </div>
                            {% for comment in ad.comments %}
                                <div class="bg-secondary rounded mb-3 p-3">
                                    <strong>{{ comment.author.firstName }}</strong> a dit :
                                    <blockquote>{{ comment.content }}</blockquote>
                                    <strong>Note donnée : </strong>
                                    {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-warning mb-0">
                                <i class="fas fa-info-circle"></i>
                                <span>Cette annonce n'a pas encore reçu de commentaires.</span>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                {% set a = ad.author %}
                <div class="row">
                    <div class="col-12">
                        <div class="card border-info p-3">
                            <div class="card-header d-flex flex-column align-items-center">
                                <img src="{{ a.picture }}" class="rounded-circle" width="100px" alt="Avatar de {{ a.fullName }}">
                                <div class="my-3 text-center">
                                    <a href="{{ path('user_show', {'slug': a.slug}) }}" class="text-info"><h3 class="my-0">{{ a.fullName }}</h3></a>
                                    <div class="text-muted">{{ a.email }}</div>
                                </div>
                                <div class="badge badge-info mx-auto">{{ a.ads |length }} annonces</div>
                            </div>
                            <div class="card-body">
                                <div class="card-text">{{ a.description | raw }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}